### PR TITLE
Build improvements; bug fix 

### PR DESCRIPTION
**Pull request by ppine7**
-- Build improvements: create a "slim" jar , without including all dependencies in it, but instead reference all dependencies via MANIFEST from the /lib dir;
-- fix a bug: indexer app can "hang" during Kafka nodes restart

### CODE REVIEW

**Comment by reachkrishnaraj** [comment]
Hi Marina, you have full access on the repo and you can merge directly to the 2.0 branch if you wish to. I see conflicts for this merge request. I will work on resolving and merging it. Thanks.

**Comment by ppine7** [comment]
Will resolve conflicts on a different branch

**Comment by ppine7** [comment]
Thanks, Krishna!
I fixed a couple more things and merged everything together. The run_indexer script should simplify running of the app a lot.

**Comment by reachkrishnaraj** [comment]
Sure, Thank You !

**Pull request closed without merging**
